# @package _global_

defaults:
  - /config@_global_
  - /flowmpc/fm/policy@_global_
  - _self_

flowmpc_train_mode: frozen
flowmpc_train_task_ids: null
flowmpc_eval_task_ids: null
tdmpc_checkpoint: null
fm_checkpoint: null
bc_coef: 1.0
